version: '3.7'

services:
  db:
      container_name: db
      build: 
        context: .
        dockerfile: Dockerfile.Development
      command: >
          bash -c "
          chmod 644 /etc/mysql/conf.d/*.cnf
          && /entrypoint.sh mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
          "
      ports: 
        - "3309:3306"
      volumes:
        - ./data:/var/lib/mysql/
        - ./conf/custom.cnf:/etc/mysql/conf.d/custom.cnf
        - ./scripts:/docker-entrypoint-initdb.d
      environment:
        MYSQL_USER: ${DB_USERNAME}
        MYSQL_DATABASE: ${DB_DATABASE}
        MYSQL_PASSWORD: ${DB_PASSWORD}
        MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD} 

volumes:
  dbdata:
    driver: local      
